version: '3.7'

x-logging:
  driver: json-file
  options:
    max-file: '5'
    max-size: 1m

services:
  adb-docker-demo:
    image: ghcr.io/pico-developer/securemr_tool:v0
    platform: linux/amd64
    container_name: securemr_tool
    network_mode: "host"  
    volumes:
      - .:/app
    environment:
      - ANDROID_ADB_SERVER_ADDRESS=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"    
    stdin_open: true # docker run -i
    tty: true        # docker run -t
